// Patch existing orgs with new fields
// Run: node /tmp/seed_patch.js (from india-csr-tracker folder)
require('dotenv').config({ path: '.env.local' })
const { createClient } = require('@supabase/supabase-js')
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY)

const PATCHES = [
  { name: 'Tata Trusts', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: ₹75 Cr committed to healthcare systems in tribal Jharkhand; Tata Water Mission MHM programme covering 900 villages in Maharashtra and Odisha; ₹50 Cr+ to education partnerships across Bihar and Rajasthan.' },
  { name: 'Azim Premji Foundation', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'both', recent_investments: 'Oct 2024: ₹500 Cr grant to CMC Vellore for medical college. Aug 2024: ₹1,500 Cr over 3 years for Karnataka mid-day meal eggs programme. Early-stage grants in Jharkhand, Odisha, NE India.' },
  { name: 'Reliance Foundation', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: Reliance Foundation scholarships disbursed to 50,000+ students. Rural health missions in Gujarat and Rajasthan. Women-led SHG programme in UP and Bihar.' },
  { name: 'Infosys Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'open', application_window: 'Rolling (Aarohan Awards annual)', recent_investments: '2025 Aarohan Awards: ₹2 Cr total prize pool for social innovation. Healthcare infrastructure grants in Karnataka. Library and sanitation projects in TN and AP.' },
  { name: 'HCL Foundation', ngo_size_preference: 'growing', grant_tier: 'large', application_type: 'open', application_window: 'Annual (typically Jan–Mar)', recent_investments: 'FY2025: ₹15 Cr committed via HCLTech Grant — 3 winners in Education, Health, Environment. Since inception: ₹135+ Cr to 200+ NGOs across 24 states.' },
  { name: 'Hindustan Unilever Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'both', recent_investments: 'FY2024: Project Shakti expanded to 135,000 women micro-entrepreneurs across 18 states. Water conservation reached 1.2M people. Sanitary pad distribution in rural UP and Bihar.' },
  { name: 'EdelGive Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'open', application_window: 'Rolling grants; EdelGive Hurun report annual', recent_investments: 'FY2024: 85 NGO partners funded. Focus on women-led organisations. GEDI (Gender, Equity, Diversity, Inclusion) lens applied to all grants. Average grant: ₹50L over 2 years.' },
  { name: 'Rohini Nilekani Philanthropies', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'invite', recent_investments: 'FY2024: Grants to 120+ partners across gender equity, mental health, environment, and active citizenship. Average grant ₹40L, multi-year. New focus: civic tech and access to justice.' },
  { name: 'Axis Bank Foundation', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: 2 million household target reached. 100+ NGO partners. ₹10 Cr avg multi-year partnership. Focus: sustainable livelihoods in Rajasthan, UP, Bihar, Odisha.' },
  { name: 'HDFC Bank Parivartan', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'both', application_window: 'SmartUp: annual; Core: rolling', recent_investments: 'FY2024: ₹800 Cr+ CSR spend. SmartUp accelerator: 200+ social startups funded. Education camps: 1.2M students. Rural development in 1,000+ villages.' },
  { name: 'Godrej Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'both', recent_investments: 'FY2024: Salon-i trained 12,000+ women. Mangrove conservation: 1,000 acres in Maharashtra. LGBTQ+ inclusion programme expanded to 5 cities.' },
  { name: 'SBI Foundation', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'open', application_window: 'Annual (typically Q4)', recent_investments: 'FY2025: ₹90 Cr Platinum Jubilee Asha Scholarship covering 23,000+ students. Healthcare grants in rural UP and Bihar. Skill development programmes in 8 states.' },
  { name: 'ONGC Foundation', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'open', application_window: 'Annual via CSR portal', recent_investments: 'FY2024: SC/ST scholarships: 2,600 students. Rural healthcare centres: 48 new facilities. Swachh Bharat initiatives in Gujarat and Rajasthan.' },
  { name: 'ITC Limited CSR', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: Mission Sunehra Kal covered 200,000+ women in SHGs. Watershed development: 1.1M acres. Digital literacy for 500,000 youth. Agri-business hubs in 5 states.' },
  { name: 'P&G India – Whisper CSR', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'both', recent_investments: 'FY2024: Spotlight Red (UNESCO) teaching modules deployed in 10 states. Period education reached 8M girls. School WASH infrastructure upgraded in 200 schools.' },
  { name: 'Dasra', ngo_size_preference: 'growing', grant_tier: 'small', application_type: 'open', application_window: 'Accelerator cohorts annual', recent_investments: 'FY2024: Dasra Philanthropy Week convened 500+ donors. MHM sector report published. Adolescent girls accelerator: 15 NGOs funded. Pooled fund for women\'s health: ₹25 Cr.' },
  { name: 'Cipla Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'invite', recent_investments: 'FY2024: Mobile healthcare vans: 180,000 consultations. Reproductive health programme in Maharashtra: 45,000 women. HIV/AIDS support in Delhi and Mumbai expanded.' },
  { name: 'Marico Innovation Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'open', application_window: 'Scale for Good: annual cohort', recent_investments: 'FY2024: Scale for Good cohort 8 — 20 social innovators selected. ₹2 Cr disbursed. Women-led enterprises: 40% of portfolio. Rural livelihoods in Maharashtra.' },
  { name: 'Wipro Cares', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: Primary education: 2.1M children reached. Ecological restoration: 500,000 trees planted. Paediatric health: Niramaya partnership reaching 80,000 children.' },
  { name: 'Tech Mahindra Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'invite', recent_investments: 'FY2024: SMART schools: 250 schools upgraded. MahaHeal IT: telemedicine in 50 rural clinics. 200+ NGO partners. Employability programme: 150,000 youth skilled.' },
  { name: 'Dr. Reddy\'s Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'invite', recent_investments: 'FY2024: LABS programme: 800,000 youth skilled since inception. DISHA rural health: 400 villages covered in AP and Telangana. Livelihood enhancement: 50,000 women.' },
  { name: 'Kotak Education Foundation', ngo_size_preference: 'grassroots', grant_tier: 'small', application_type: 'open', application_window: 'Annual (Mumbai-focused)', recent_investments: 'FY2024: 12,000 scholarships disbursed. Vocational training: 8,000 youth in Mumbai slums. Girl child education in Dharavi and Govandi. First-generation learners: 70% of recipients.' },
  { name: 'Gates Foundation India', ngo_size_preference: 'large', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: Maternal health investments in UP and Bihar. Polio eradication programme: last-mile coverage. Agricultural productivity: 2M smallholder farmers. Financial inclusion for 10M women via PMJDY.' },
  { name: 'Arghyam Foundation', ngo_size_preference: 'growing', grant_tier: 'small', application_type: 'open', application_window: 'Rolling proposals accepted', recent_investments: 'FY2024: WASH grants in 18 states. Menstrual waste management: 50 schools in Rajasthan and Karnataka. Water governance research: 8 states. Sanitation in tribal areas of Jharkhand.' },
  { name: 'Aditya Birla Foundation', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: 18 states, 7,500+ villages. Education: 400,000 students. Healthcare: 1.2M beneficiaries. WASH: 100,000 households. Livelihoods: 80,000 women through SHGs.' },
  { name: 'L&T Foundation', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: Technical education: 200,000 youth. Infrastructure in Maharashtra and TN. Rural development in L&T operational areas. STEM education in government schools.' },
  { name: 'JSW Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'both', recent_investments: 'FY2024: Parvaah — women\'s empowerment in 300 villages near JSW plants. Education: 50,000 children. Sports infrastructure: 20 academies. Healthcare: 200,000 beneficiaries in Karnataka.' },
  { name: 'Mahindra Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'open', application_window: 'Nanhi Kali: rolling applications', recent_investments: 'FY2024: Nanhi Kali: 1.5M girls supported with education and menstrual hygiene kits. K.C. Mahindra Scholarships: 1,200 awards. Hariyali: 500,000 trees planted.' },
  { name: 'Bajaj Foundation', ngo_size_preference: 'grassroots', grant_tier: 'small', application_type: 'invite', recent_investments: 'FY2024: Integrated rural development in Wardha: 80,000 families. Women\'s SHGs: 5,000 groups. Menstrual health camps in Rajasthan: 12,000 women reached.' },
  { name: 'Biocon Foundation', ngo_size_preference: 'grassroots', grant_tier: 'small', application_type: 'invite', recent_investments: 'FY2024: Mobile health units: 250,000 consultations. Women\'s reproductive health in Karnataka: 30,000 women. Diabetes screening in 100 villages near Bangalore.' },
  { name: 'Swades Foundation', ngo_size_preference: 'growing', grant_tier: 'medium', application_type: 'invite', recent_investments: 'FY2024: 100% village coverage in Raigad district (560 villages). WASH: 18,000 toilet construction. Women\'s dignity kits distributed. Digital literacy: 20,000 youth.' },
  { name: 'Shiv Nadar Foundation', ngo_size_preference: 'large', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: VidyaGyan: 2,500 rural scholars on full scholarships. SSN Institutions: 14,000 students. Shiv Nadar University: expanded research grants. Focus: transformative education at scale.' },
  { name: 'Vedanta Foundation (Nand Ghar)', ngo_size_preference: 'established', grant_tier: 'large', application_type: 'invite', recent_investments: 'FY2024: 7,200+ Nand Ghars operational. Early childhood nutrition: 500,000 children. Women\'s health centres: 200 facilities in Rajasthan and Odisha.' },
  { name: 'Mariwala Health Initiative', ngo_size_preference: 'grassroots', grant_tier: 'small', application_type: 'open', application_window: 'Annual call for proposals', recent_investments: 'FY2024: 25 mental health organisations funded. Women\'s mental health: GBV survivor support in 6 cities. Community psychosocial workers trained: 800.' },
  { name: 'Piramal Foundation', ngo_size_preference: 'established', grant_tier: 'medium', application_type: 'invite', recent_investments: 'FY2024: Piramal Swasthya: telemedicine in 25,000+ villages. Mobile health vans: 3M consultations. Tribal health in MP: 800,000 beneficiaries. Education leadership programme: 500 district officials.' },
]

async function patch() {
  console.log('🔧 Patching organisations with Navigator fields...')
  let ok = 0, fail = 0
  for (const p of PATCHES) {
    const { name, ...fields } = p
    const { error } = await sb.from('organisations').update(fields).eq('name', name)
    if (error) { console.error(`  ✗ ${name}:`, error.message); fail++ }
    else { console.log(`  ✓ ${name}`); ok++ }
  }
  console.log(`\n✅ Done. ${ok} patched, ${fail} failed.`)
}
patch().catch(console.error)
